"use client";
import { useMemo, useRef, useState } from "react";
type Card={name:string;ko:string;arcana:string;symbol:string;light:string;shadow:string;image:string};
type Drawn=Card&{reversed:boolean;revealed:boolean};
const majors=[
["The Fool","바보","0","✦","새로운 시작 · 자유 · 가능성","무모함 · 주저 · 준비 부족"],["The Magician","마법사","I","✧","의지 · 창조 · 실행력","기만 · 산만함 · 재능의 낭비"],["The High Priestess","여사제","II","☾","직관 · 침묵 · 내면의 앎","혼란 · 비밀 · 직관의 외면"],["The Empress","여제","III","❀","풍요 · 돌봄 · 성장","과보호 · 정체 · 결핍"],["The Emperor","황제","IV","♜","질서 · 책임 · 통제","경직 · 독선 · 통제 상실"],["The Hierophant","교황","V","♙","전통 · 배움 · 약속","관습 거부 · 독단 · 불일치"],["The Lovers","연인","VI","♡","선택 · 결합 · 가치의 일치","불화 · 망설임 · 가치 충돌"],["The Chariot","전차","VII","♞","전진 · 승리 · 의지","폭주 · 지연 · 방향 상실"],["Strength","힘","VIII","∞","용기 · 인내 · 부드러운 힘","불안 · 자기 의심 · 억압"],["The Hermit","은둔자","IX","⌁","성찰 · 탐구 · 거리두기","고립 · 회피 · 길을 잃음"],["Wheel of Fortune","운명의 수레바퀴","X","◉","전환 · 기회 · 순환","저항 · 불운 · 반복"],["Justice","정의","XI","⚖","균형 · 판단 · 책임","불공정 · 편견 · 책임 회피"],["The Hanged Man","매달린 사람","XII","◇","관점 전환 · 멈춤 · 수용","희생 강요 · 지연 · 고집"],["Death","죽음","XIII","✢","종결 · 변화 · 재생","변화 거부 · 미련 · 정체"],["Temperance","절제","XIV","△","조화 · 치유 · 조율","과잉 · 불균형 · 충돌"],["The Devil","악마","XV","♢","욕망 · 집착 · 속박","해방 · 자각 · 통제 회복"],["The Tower","탑","XVI","ϟ","붕괴 · 폭로 · 급변","위기 회피 · 불안 · 잔여 충격"],["The Star","별","XVII","✷","희망 · 회복 · 영감","실망 · 불신 · 무기력"],["The Moon","달","XVIII","☽","무의식 · 불확실 · 상상","혼란 해소 · 진실 · 직면"],["The Sun","태양","XIX","☼","기쁨 · 명료함 · 성공","지연된 기쁨 · 과신 · 피로"],["Judgement","심판","XX","♬","각성 · 결단 · 부름","자기 의심 · 후회 · 회피"],["The World","세계","XXI","◎","완성 · 통합 · 성취","미완 · 지연 · 마무리 필요"]] as string[][];
const major:Card[]=majors.map(([name,ko,arcana,symbol,light,shadow],i)=>({name,ko,arcana,symbol,light,shadow,image:`/cards/major-${String(i).padStart(2,"0")}.webp`}));
const suits=[{name:"Wands",ko:"완드",symbol:"♣",light:"열정 · 행동 · 추진",shadow:"소진 · 충돌 · 지연"},{name:"Cups",ko:"컵",symbol:"♥",light:"감정 · 관계 · 공감",shadow:"감정 기복 · 거리 · 미련"},{name:"Swords",ko:"소드",symbol:"◆",light:"판단 · 진실 · 결단",shadow:"갈등 · 불안 · 오판"},{name:"Pentacles",ko:"펜타클",symbol:"●",light:"현실 · 성과 · 안정",shadow:"정체 · 손실 · 집착"}];
const ranks=["Ace","2","3","4","5","6","7","8","9","10","Page","Knight","Queen","King"], rankKo:Record<string,string>={Ace:"에이스",Page:"페이지",Knight:"나이트",Queen:"퀸",King:"킹"};
const minor:Card[]=suits.flatMap(s=>ranks.map((rank,i)=>({name:`${rank} of ${s.name}`,ko:`${rankKo[rank]??rank} 오브 ${s.ko}`,arcana:String(i+1),symbol:s.symbol,light:`${s.light} · ${["시작","균형","확장","기반","변화","회복","점검","숙련","지속","완결","소식","전진","성숙","통솔"][i]}`,shadow:s.shadow,image:`/cards/${s.name.toLowerCase()}-${String(i+1).padStart(2,"0")}.webp`})));
const deck=[...major,...minor];
const spreads=[
 {id:"one",label:"원 카드",count:1,desc:"한 가지 핵심 메시지",positions:["핵심 메시지"]},
 {id:"two",label:"2카드",count:2,desc:"두 요소를 나란히 비교",positions:["첫 번째 관점","두 번째 관점"]},
 {id:"three",label:"3카드",count:3,desc:"흐름을 간결하게 살펴봅니다",positions:["과거 · 배경","현재 · 핵심","미래 · 방향"]},
 {id:"four",label:"4카드",count:4,desc:"상황을 네 방향에서 점검",positions:["현재 상황","장애물","조언","결과"]},
 {id:"five",label:"5카드",count:5,desc:"상황과 조언을 균형 있게",positions:["현재 상황","장애물","숨은 영향","조언","결과"]},
 {id:"seven",label:"7카드",count:7,desc:"일곱 단계의 흐름을 확인",positions:["시작","과거","현재","핵심","가까운 미래","조언","결과"]},
 {id:"mini-celtic",label:"미니 켈틱",count:6,desc:"핵심만 압축한 켈틱 크로스",positions:["현재 상황","장애물","기저","과거","가능성","결과"]},
 {id:"horseshoe",label:"말발굽",count:7,desc:"과거부터 결과까지 넓게",positions:["과거","현재","가까운 미래","조언","주변 영향","장애물","결과"]},
 {id:"magic-seven",label:"매직 세븐",count:7,desc:"내면과 외부 흐름을 함께",positions:["과거","현재","가까운 미래","나의 태도","주변 상황","장애물","결과"]},
 {id:"relationship",label:"릴레이션십",count:7,desc:"두 사람과 관계의 중심",positions:["나의 생각","나의 감정","나의 태도","관계의 핵심","상대의 태도","상대의 감정","상대의 생각"]},
 {id:"choice",label:"양자택일",count:5,desc:"두 선택의 과정과 결과 비교",positions:["현재 상황","A의 과정","B의 과정","A의 결과","B의 결과"]},
 {id:"celtic",label:"켈틱 크로스",count:10,desc:"한 질문을 깊고 입체적으로",positions:["현재 상황","장애물","무의식 · 기저","가까운 과거","의식 · 예상","가까운 미래","자기 인식","주변 환경","희망 · 두려움","결과"]}
];
export default function Home(){
 const[spreadId,setSpreadId]=useState("three"),[question,setQuestion]=useState(""),[reversals,setReversals]=useState(true),[revealMode,setRevealMode]=useState<"manual"|"auto">("manual"),[cards,setCards]=useState<Drawn[]>([]),[copied,setCopied]=useState(false),[positionOpen,setPositionOpen]=useState(false),[positionStarted,setPositionStarted]=useState(false),[positionNames,setPositionNames]=useState([...spreads.find(s=>s.id==="three")!.positions]);const sequenceRef=useRef(0);const spread=spreads.find(s=>s.id===spreadId)!;const positions=positionNames.map((name,i)=>name.trim()||`${i+1}번 자리`);const complete=cards.length>0&&cards.every(c=>c.revealed);
 const summary=useMemo(()=>complete?[`## 질문 : ${question||"기록하지 않음"}`,"",`## ${spread.label} 스프레드`,"",...cards.map((c,i)=>`${i+1}. ${positions[i]} : ${c.name}${c.reversed?" (역방향)":""}`),"","## 리딩 메모","","카드 뜻을 따로 나열하기보다 카드 간 연결과 전체 흐름 중심으로 해석합니다."].join("\n"):"",[cards,complete,question,spread,positions]);
 function chooseSpread(id:string){const next=spreads.find(s=>s.id===id)!;sequenceRef.current++;setSpreadId(id);setPositionNames([...next.positions]);setPositionStarted(false);setPositionOpen(false);setCards([])}
 function togglePositionEditor(){if(!positionOpen&&!positionStarted){setPositionNames(Array(spread.count).fill(""));setPositionStarted(true)}setPositionOpen(v=>!v)}
 function draw(){const shuffled=[...deck].sort(()=>Math.random()-.5).slice(0,spread.count);sequenceRef.current++;setCards(shuffled.map(c=>({...c,reversed:reversals&&Math.random()<.28,revealed:revealMode==="auto"})));setCopied(false)}
 function reveal(index:number){setCards(p=>p.map((c,i)=>i===index?{...c,revealed:true}:c))}async function copy(){await navigator.clipboard.writeText(summary);setCopied(true);window.setTimeout(()=>setCopied(false),1600)}
 return <main><header className="topbar"><a className="brand" href="#top"><span className="brand-mark">☾</span><span>달빛 타로</span></a><span className="tagline">질문은 가볍게, 해석은 깊게</span></header>
 <section className="hero" id="top"><div className="constellation one">✦</div><div className="constellation two">✧</div><p className="eyebrow">A QUIET READING FOR YOUR QUESTION</p><h1>마음속 질문을<br/><em>카드에게 건네보세요.</em></h1><p className="hero-copy">78장의 카드에서 한 번의 흐름을 뽑습니다.<br/>정답보다, 지금 보지 못한 방향을 발견하기 위한 리딩입니다.</p><a className="start-link" href="#reading">리딩 시작하기 <span>↓</span></a></section>
 <section className="reading-shell" id="reading"><div className="section-heading"><span>01</span><div><p>SPREAD</p><h2>어떤 방식으로 살펴볼까요?</h2></div></div><div className="spread-grid">{spreads.map(s=><button key={s.id} className={`spread-option ${spreadId===s.id?"active":""}`} onClick={()=>chooseSpread(s.id)}><span className="mini-cards">{Array.from({length:Math.min(s.count,5)}).map((_,i)=><i key={i}/>)}</span><strong>{s.label}</strong><small>{s.desc}</small><b>{s.count} CARDS</b></button>)}</div>
 <div className="question-panel"><div className="question-head"><label htmlFor="question"><span>02</span><div><small>YOUR QUESTION</small><strong>무엇이 궁금하신가요?</strong></div></label><button className={`position-toggle ${positionOpen?"active":""}`} onClick={togglePositionEditor} aria-expanded={positionOpen}>자리 설정 <span>{positionOpen?"−":"+"}</span></button></div>{positionOpen&&<div className="position-editor"><p>각 카드가 뜻하는 자리를 직접 적어주세요.</p><div>{positionNames.map((name,i)=><label key={i}><span>{i+1}.</span><input aria-label={`${i+1}번 자리`} value={name} maxLength={24} onChange={e=>setPositionNames(p=>p.map((v,n)=>n===i?e.target.value:v))}/></label>)}</div><button onClick={()=>setPositionNames([...spread.positions])}>기본값으로 되돌리기</button></div>}<div className="question-input-row"><textarea id="question" maxLength={120} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="예: 지금 쓰고 있는 작품의 다음 흐름은 어떻게 될까요?"/><button className="redraw" onClick={draw} disabled={!cards.length}><span>↻</span>새로 뽑기</button></div><div className="question-foot"><span>{question.length} / 120</span><div className="reading-options"><div className="mode-select" aria-label="카드 공개 방식"><span>카드 공개</span><button className={revealMode==="manual"?"active":""} aria-pressed={revealMode==="manual"} onClick={()=>setRevealMode("manual")}>수동</button><button className={revealMode==="auto"?"active":""} aria-pressed={revealMode==="auto"} onClick={()=>setRevealMode("auto")}>자동</button></div><label className="toggle"><input type="checkbox" checked={reversals} onChange={e=>setReversals(e.target.checked)}/><i/><span>역방향 포함</span></label></div></div></div>
 <div className="draw-zone">{!cards.length?<><div className="deck-stack"><i/><i/><div><span>☾</span><b>✦</b></div></div><p>숨을 고르고 질문을 한 번 떠올려 보세요.</p><button className="primary" onClick={draw}>카드 섞고 뽑기 <span>✦</span></button></>:<><div className={`cards-layout ${spreadId}`}>{cards.map((c,i)=><article key={`${c.name}-${i}`} className={`tarot-card ${c.revealed?"revealed":""} ${c.reversed?"reversed":""}`} onClick={()=>reveal(i)}><div className="card-inner"><div className="card-back"><span>☾</span><i>✦</i><small>{i+1}</small></div><div className="card-face"><img src={c.image} alt={`${c.ko} — ${c.name}`}/></div></div><div className="position"><span>{String(i+1).padStart(2,"0")}</span><div>{positions[i]}{c.reversed&&<small>역방향</small>}</div></div></article>)}</div>{!complete&&<button className="ghost" onClick={()=>setCards(p=>p.map(c=>({...c,revealed:true})))}>모든 카드 펼치기</button>}</>}</div>
 {complete&&<section className="result-panel"><div className="result-title"><div><small>YOUR READING</small><h2>카드가 전하는 흐름</h2></div><button onClick={copy}>{copied?"복사했습니다":"결과 복사"}</button></div><div className="interpretations">{cards.map((c,i)=><div key={i}><span>{i+1}</span><div><small>{positions[i]}</small><h3>{c.name} {c.reversed&&<em>역방향</em>}</h3><p>{c.reversed?c.shadow:c.light}</p></div></div>)}</div><div className="note"><span>✦</span><p><strong>리딩 팁</strong>개별 의미를 나열하기보다 앞 카드가 만든 원인, 가운데의 변화, 마지막 카드가 향하는 방향을 한 문장으로 먼저 연결해 보세요.</p></div><button className="reset" onClick={()=>{sequenceRef.current++;setCards([]);setQuestion("");window.location.hash="reading"}}>새로운 질문으로 다시 뽑기 ↻</button></section>}</section>
 <footer><span className="brand-mark">☾</span><p>달빛 타로</p><small>카드는 선택을 대신하지 않습니다. 당신의 마음을 비추는 거울로 활용해 주세요.</small><small className="credit">카드 이미지: Pamela Colman Smith, 1909 Roses &amp; Lilies edition · <a href="https://commons.wikimedia.org/wiki/Category:Rider-Waite_tarot_deck_(Roses_%26_Lilies)" target="_blank" rel="noreferrer">Wikimedia Commons</a> · Public Domain</small></footer></main>}
